const projects = [
    {
        id: 1,
        name: 'U Tracker',
        desc: 'An application to track your all data from one place. I developed the website and the mobile app',
        img: 'https://i.postimg.cc/pVcSWx2q/utracker.jpg',
        live: 'dfad',
        code: 'asdfasdf',
    },
    {
        id: 2,
        name: 'Green CTG',
        desc: 'An app to help people to get an overview of how they can make the city beautiful.',
        img: 'https://i.postimg.cc/pVcSWx2q/utracker.jpg',
        live: 'dfad',
        code: 'asdfasdf',
    },
    {
        id: 3,
        name: 'Coin Tracker',
        desc: 'Using this app you can track any e coin. Also you will get a good advise about investment form the professional',
        img: 'https://i.postimg.cc/pVcSWx2q/utracker.jpg',
        live: 'dfad',
        code: 'asdfasdf',
    },
    {
        id: 4,
        name: "Cavin's Portfolio",
        desc: 'A portfolio for Cavin jr. A artist from New york city. The portfolio is made using ReactJs and GatsbyJs.',
        img: 'https://i.postimg.cc/pVcSWx2q/utracker.jpg',
        live: 'dfad',
        code: 'asdfasdf',
    },
    {
        id: 5,
        name: 'Tracking Soft',
        desc: 'A tracking website that will show the performance of the website. Also you will get some useful advice to improve the performance.',
        img: 'https://i.postimg.cc/pVcSWx2q/utracker.jpg',
        live: 'dfad',
        code: 'asdfasdf',
    },
    {
        id: 6,
        name: 'Tracking Soft',
        desc: 'A tracking website that will show the performance of the website. Also you will get some useful advice to improve the performance.',
        img: 'https://i.postimg.cc/pVcSWx2q/utracker.jpg',
        live: 'dfad',
        code: 'asdfasdf',
    },
];
export default projects;